### ISSUE TITLE
The reward event does not work.

### ISSUE THREAD

**Issue by ChrisTVH** [SerbanHiro/ToastedAFK#5]
## Description of the problem
- Before the plugin worked fine, but after I upgraded the server to 1.21, it worked fine, but then I was upgrading more plugins (like fawe )and to other versions of 1.21 at some point it broke.
- Here is the log of the error that appears when you go to an afk zone: https://mclo.gs/lThGPpT
### Server information
- UniverseSpigot version 1.21-DEV-ver/1.21@a62044c
- ToastedAFK 2.0.2

**Comment by SerbanHiro** [comment]
Should be fixed, try latest ver

**Comment by ChrisTVH** [comment]
> Should be fixed, try latest ver

Now it does not start the plugin at all.
https://mclo.gs/oJudKnt

**Comment by SerbanHiro** [comment]
Try with latest ver 2.0.2.2

**Comment by ChrisTVH** [comment]
It already starts correctly, but this time I tested it on a test server.
I have noticed that if in server.properties the level name is other, the plugin does not automatically detect the world name and gives an error.

https://mclo.gs/vlaxhgy

**Comment by SerbanHiro** [comment]
Make sure you update the world inside config.yml too, it's not meant to auto detect it, u gotta put it through /tafk save

**Comment by ChrisTVH** [comment]
> Make sure you update the world inside config.yml too, it's not meant to auto detect it, u gotta put it through /tafk save

I was just telling you because other plugins generated the config based on the world, leaving that aside it works fine.

**Comment by SerbanHiro** [comment]
Ohh I see, glad it works
